name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: setup
      run: yarn
    - name: test
      run: yarn test
    - name: build
      run: yarn build
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.2.4
      with:
        # Build directory to deploy
        build_dir: build
